# 最低限のコードformatter設定
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

# 基本的なフォーマットルールのみ有効化
Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/TrailingWhitespace:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

# その他のルールは無効化
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
